In [7]:
conda install pytorch::pytorch torchvision torchaudio -c pytorch

Channels:
 - pytorch
 - defaults
 - conda-forge
Platform: osx-arm64
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/AI_Ocean

  added / updated specs:
    - pytorch::pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aom-3.12.1                 |       ha237518_0         2.4 MB
    brotlicffi-1.2.0.0         |  py312h50f4ffc_0         365 KB
    ca-certificates-2025.12.2  |       hca03da5_0         125 KB
    cairo-1.18.4               |       h191e429_0         626 KB
    certifi-2026.01.04         |  py312hca03da5_0         148 KB
    cffi-2.0.0                 |  py312h73c2a22_1         279 KB
    charset-normalizer-3.4.4   |  py312hca03da5_0          97 KB
    filelock-3.20.3            |  py312hca03da5_0          38 KB
    fontconfig-2.15.0          |       h29935d0_0         225 KB
    freetype-2.14

In [9]:
import torch

def check_mps_availability():
    # MPS 사용 가능 여부를 확인합니다.
    if torch.backends.mps.is_available():
        print("이 장치에서 MPS(GPU 가속)를 사용할 수 있습니다.")
    else:
        print("MPS를 사용할 수 없습니다. CPU를 사용합니다.")

#  GPU 사용 가능 여부를 확인합니다.
check_mps_availability()

이 장치에서 MPS(GPU 가속)를 사용할 수 있습니다.


In [10]:
import torch
import math
dtype = torch.float
device = torch.device("mps")

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(5000):
    # Forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

# Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights using gradient descent
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 587.0638427734375
199 391.2157897949219
299 261.7015380859375
399 176.05349731445312
499 119.41376495361328
599 81.95762634277344
699 57.187217712402344
799 40.805885314941406
899 29.972692489624023
999 22.808353424072266
1099 18.070343017578125
1199 14.936897277832031
1299 12.86457347869873
1399 11.494050979614258
1499 10.587628364562988
1599 9.988134384155273
1699 9.591635704040527
1799 9.329414367675781
1899 9.155985832214355
1999 9.041275024414062
2099 8.965404510498047
2199 8.915220260620117
2299 8.882030487060547
2399 8.860069274902344
2499 8.845547676086426
2599 8.835943222045898
2699 8.829587936401367
2799 8.825385093688965
2899 8.822604179382324
2999 8.820764541625977
3099 8.819547653198242
3199 8.818741798400879
3299 8.81821060180664
3399 8.817856788635254
3499 8.817623138427734
3599 8.817468643188477
3699 8.817367553710938
3799 8.817299842834473
3899 8.817255020141602
3999 8.817225456237793
4099 8.817205429077148
4199 8.817192077636719
4299 8.817184448242188
4399 8.817177

In [11]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.9308, 0.2158, 0.1892],
        [0.3568, 0.5956, 0.6517],
        [0.0932, 0.4890, 0.1014],
        [0.4852, 0.6307, 0.1118],
        [0.5901, 0.6947, 0.6425]])


In [12]:
# 텐서(Tensor)

import torch
import numpy as np

In [13]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [14]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [16]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8154, 0.9593],
        [0.8997, 0.7548]]) 



In [ ]:
####################################################################################################################################
####################################################################################################################################

In [ ]:
# 파이토치를 이용한 모델 구조 구축

import torch
import torch.nn as nn

class OceanModel(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.convlstm = ConvLSTM(...) # 시간 처리
        self.unet = UNet(...) # 공간 처리
    
    def forward(self, x):
        x = self.convlstm(x) # time 정보 반영된 feature map
        x = self.unet(x) # 지도 형태로 복원
        return x

In [ ]:
# Layer 정의

nn.Conv2d()
nn.MaxPool2d()
nn.ConvTranspose2d()

In [ ]:
# 블록 만들기

Conv → ReLU → Conv

In [ ]:
# 전체 연결

Encoder → Bottleneck → Decoder

In [ ]:
# forward 함수 데이터 흐름 정의

# 성능, 메모리, 학습 가능 여부가 결정됨

In [ ]:
# ConvLSTM -> U-Net 연결

x, _ = self.convlstm(x)
x = x[:, -1]   # 마지막 time step만 사용
x = self.unet(x)

# 방법 1

# ConvLSTM -> 마지막 output -> U-Net

# 방법 2

# ConvLSTM -> 모든 time step -> 3D U-Net

In [ ]:
# .nc 파일 → Dataset → DataLoader → Model → Loss → 학습

In [33]:
import glob

so_files     = sorted(glob.glob("/Users/minji/Desktop/ocean_raw/so/*.nc"))
thetao_files = sorted(glob.glob("/Users/minji/Desktop/ocean_raw/thetao/*.nc"))
uo_files     = sorted(glob.glob("/Users/minji/Desktop/ocean_raw/uo/*.nc"))
vo_files     = sorted(glob.glob("/Users/minji/Desktop/ocean_raw/vo/*.nc"))
zos_files    = sorted(glob.glob("/Users/minji/Desktop/ocean_raw/zos/*.nc"))

tas_files  = sorted(glob.glob("/Users/minji/Desktop/atmos_remap_1deg/tas/*.nc"))
uas_files  = sorted(glob.glob("/Users/minji/Desktop/atmos_remap_1deg/uas/*.nc"))
vas_files  = sorted(glob.glob("/Users/minji/Desktop/atmos_remap_1deg/vas/*.nc"))
huss_files = sorted(glob.glob("/Users/minji/Desktop/atmos_remap_1deg/huss/*.nc"))
rsns_files = sorted(glob.glob("/Users/minji/Desktop/atmos_remap_1deg/rsns/*.nc"))

In [34]:
print(len(so_files))
print(len(thetao_files))
print(len(uo_files))
print(len(vo_files))
print(len(zos_files))

1
1
1
1
1


In [48]:
import torch
from torch.utils.data import Dataset
import xarray as xr
import torch.nn.functional as F

class OceanDataset(Dataset):
    def __init__(self,
                 so_files, thetao_files, uo_files, vo_files, zos_files,
                 tas_files, uas_files, vas_files, huss_files, rsns_files):

        self.so = so_files
        self.thetao = thetao_files
        self.uo = uo_files
        self.vo = vo_files
        self.zos = zos_files

        self.tas = tas_files
        self.uas = uas_files
        self.vas = vas_files
        self.huss = huss_files
        self.rsns = rsns_files

    def __len__(self):
        return 1 ## 기존 return len(self.so) - 4
    
    def __getitem__(self, idx):
        
        # ocean
        ds_o = xr.open_dataset(self.so[0])
        so = ds_o['so'].isel(time=0, lev=0).values

        # atm
        ds_a = xr.open_dataset(self.tas[0])
        tas = ds_a['tas'].isel(time=0).values

        # tensor
        so = torch.tensor(so).unsqueeze(0)
        tas = torch.tensor(tas).unsqueeze(0)

        # 사이즈 맞추기
        so = F.interpolate(so.unsqueeze(0), size=(180, 360)).squeeze(0)
        tas = F.interpolate(tas.unsqueeze(0), size=(180, 360)).squeeze(0)

        x = torch.cat([so, tas], dim=0)  # (C, H, W)

        x = x.unsqueeze(0)  # (T=1, C, H, W)

        y = tas  # (1, H, W) 또는 so

        return x, y

    # def __getitem__(self, idx):
    #     x_seq = []

    #     for i in range(4):  # t-3 ~ t

    #         # ===== ocean =====
    #         so = xr.open_dataset(self.so[idx+i])['so'].isel(time=0, lev=0).values
    #         th = xr.open_dataset(self.thetao[idx+i])['thetao'].isel(time=0, lev=0).values
    #         uo = xr.open_dataset(self.uo[idx+i])['uo'].isel(time=0, lev=0).values
    #         vo = xr.open_dataset(self.vo[idx+i])['vo'].isel(time=0, lev=0).values
    #         zos = xr.open_dataset(self.zos[idx+i])['zos'].isel(time=0).values

    #         # ===== atm =====
    #         tas = xr.open_dataset(self.tas[idx+i])['tas'].isel(time=0).values
    #         uas = xr.open_dataset(self.uas[idx+i])['uas'].isel(time=0).values
    #         vas = xr.open_dataset(self.vas[idx+i])['vas'].isel(time=0).values
    #         huss = xr.open_dataset(self.huss[idx+i])['huss'].isel(time=0).values
    #         rsns = xr.open_dataset(self.rsns[idx+i])['rsns'].isel(time=0).values

    #         # ===== tensor =====
    #         ocean = torch.tensor([th, so, uo, vo, zos], dtype=torch.float32)
    #         atm   = torch.tensor([tas, uas, vas, huss, rsns], dtype=torch.float32)

    #         x = torch.cat([ocean, atm], dim=0)  # (C, H, W)

    #         x_seq.append(x)

    #     x = torch.stack(x_seq)  # (T, C, H, W)

    #     # ===== downsampling =====
    #     x = F.interpolate(x, size=(180, 360))

    #     # ===== target (zos 예측) =====
    #     y = xr.open_dataset(self.zos[idx+4])['zos'].isel(time=0).values
    #     y = torch.tensor(y, dtype=torch.float32).unsqueeze(0)
    #     y = F.interpolate(y.unsqueeze(0), size=(180, 360)).squeeze(0)

    #     return x, y

In [49]:
from torch.utils.data import DataLoader

dataset = OceanDataset(
    so_files, thetao_files, uo_files, vo_files, zos_files,
    tas_files, uas_files, vas_files, huss_files, rsns_files
)

loader = DataLoader(dataset, batch_size=1, shuffle=True, num_workers=0)

In [50]:
x, y = next(iter(loader))

print(x.shape)  # (B, T, C, H, W)
print(y.shape)  # (B, 1, H, W)

torch.Size([1, 1, 2, 180, 360])
torch.Size([1, 1, 180, 360])


In [ ]:
x, y = next(iter(loader))

device = torch.device("cpu")

x = x.to(device)
y = y.to(device)

model = model.to(device)

# x = x.cuda()
# y = y.cuda()

output = model(x)

print(output.shape)

NameError: name 'model' is not defined

In [ ]:
코덱스 이용해 보기(토큰)

코드 교차 검증 코덱스 vs. 클로드

프롬프트, 계획 구체적으로(계획이 타당한지 먼저 검토)

hidden layer 개수
convLSTM(시간 정보), u-net, cnn, trasform

계획 짜고 면담 전에 시간 되면 미리 훈련해보기!